# Generated by Django 4.0.2 on 2022-02-27 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.TextField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promApp.profile')),
            ],
            options={
                'verbose_name': 'Crush',
                'verbose_name_plural': 'Crushes',
            },
        ),
    ]
